name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-14
    env:
      XCCONFIG: ${{ secrets.XCCONFIG }}
      GOOGLE_SERVICE_INFO: ${{ secrets.GOOGLE_SERVICE_INFO }}
      GOOGLE_SERVICE_INFO_DEBUG: ${{ secrets.GOOGLE_SERVICE_INFO_DEBUG }}
      FASTLANE_SKIP_UPDATE_CHECK: true
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Rubyセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Xcodeセットアップ
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: 設定ファイル生成
        run: |
          cd ci_scripts
          bash ci_post_clone.sh

      - name: ビルドとテスト
        uses: fastlane/fastlane-action@v3
        with:
          lane: ci
